#!/bin/bash
#sh auth2 Sign Beer Check 10 KFC 50 Cigarettes 25 Beer |sh auth2 Verify|tool\lprint -f -
#sh auth2 Sign Sell Chasm -45 Prod 450 Checking |sh auth2 Verify|tool\lprint -f -
#sh auth2 Sign Purchase Chasm 50 Mat -450 Wallet 50 Material |sh auth2 Verify|tool\lprint -f -

if [ "$1" = "Verify" ]; then
	src=$(cat -|tee opa2.txt|tool/jwt -key shared.txt -alg HS256 -verify - -show|grep src|awk '{print $2}'|awk -F"," '{print $1}'| tr -d '"')
	acc=$(cat opa2.txt|tool/jwt -key shared.txt -alg HS256 -verify - -show|grep acc|awk '{print $2}'|awk -F"," '{print $1}'| tr -d '"')
	ac2=$(cat opa2.txt|tool/jwt -key shared.txt -alg HS256 -verify - -show|grep ac2|awk '{print $2}'|awk -F"," '{print $1}'| tr -d '"')
	ac3=$(cat opa2.txt|tool/jwt -key shared.txt -alg HS256 -verify - -show|grep ac3|awk '{print $2}'|awk -F"," '{print $1}'| tr -d '"')
	cost=$(cat opa2.txt|tool/jwt -key shared.txt -alg HS256 -verify - -show|grep cost|awk '{print $2}'|awk -F"," '{print $1}'| tr -d '"')
	cat opa2.txt |tool/jwt -key shared.txt -alg HS256 -verify - |tool/json2csv -header-style slash >Auth.csv
	
	tool/gocsv rename -c amount -names null "Auth.csv"|tool/gocsv rename -c cost -names amount > "Auth2.csv"
	tool/gocsv rename -c amount -names null "Auth.csv"|tool/gocsv rename -c cost2 -names amount > "Auth3.csv"

	tool/limport -date-format "2006/01/02" -f main.txt -set-search "$acc" "$src" Auth.csv
	tool/limport -date-format "2006/01/02" -f main.txt -set-search "$ac2" "$src" Auth2.csv
	tool/limport -date-format "2006/01/02" -f main.txt -set-search "$ac3" "$src" Auth3.csv

	rm opa2.txt
	rm Auth.csv Auth2.csv Auth3.csv
elif [ "$1" = "Sign" ]; then
	if [ -z "$2" ]
	then
		echo "No argument supplied"
		echo "Usage: <Payee> <Amount> <Account>"
		exit 1
	fi
	uuid=$(tool/uuid)
	date=$(date '+%Y/%m/%d')
	tool/jwt -key shared.txt -alg HS256 -claim date=$date -claim payee="$2" -claim amount="$4" -claim cost="$6" -claim uuid=$uuid -header src="$3" -header acc="$5" -header ac2="$7" -claim cost2="$8" -header ac3="$9" -sign +
elif [ "$1" = "Check" ]; then
	cat - |tool/jwt -key shared.txt -alg HS256 -verify -|tool/json2csv -header-style slash
elif [ "$1" = "Parse" ]; then
	cat - |tool/jwt -key shared.txt -alg HS256 -verify -
elif [ "$1" = "Show" ]; then
	cat -|tool/jwt -key shared.txt -alg HS256 -verify - -show
fi
